### ISSUE TITLE
Pretrained model for ArcFace

### ISSUE THREAD

**Issue by seoyoung1215** [kuai-lab/sound-guided-semantic-image-manipulation#8]
Hi, 
thanks for the great work!

Could you also share the pretrained model used for ArcFace? (model_ir_se50.pth)

Thank you!

**Comment by lsh3163** [comment]
Hi,

You can find the weights of pretrained ArcFace from official StyleCLIP repository.

Thanks.

**Comment by seoyoung1215** [comment]
Thanks a lot! 👍
